name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # This will trigger the CI/CD on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Change this to your required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Adjust this if your test command is different

    - name: Build application
      run: npm run build  # Adjust if your build command is different

    - name: Deploy to Oracle Compute
      env:
        ORACLE_USER: ${{ secrets.ORACLE_USER }}  # Your Oracle Compute username
        ORACLE_HOST: ${{ secrets.ORACLE_HOST }}  # Your Oracle Compute instance IP
        ORACLE_SSH_KEY: ${{ secrets.ORACLE_SSH_KEY }}  # Your SSH private key
      run: |
        echo "${ORACLE_SSH_KEY}" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -o StrictHostKeyChecking=no -r ./build/* ${ORACLE_USER}@${ORACLE_HOST}:/path/to/your/deployment/directory
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${ORACLE_USER}@${ORACLE_HOST} 'cd /path/to/your/deployment/directory && npm install && pm2 restart your-app-name'  # Adjust this command as necessary
